[project]
name = "CHANGE_ME"
version = "0.1.0"
requires-python = ">=3.12"
# license = { file = "LICENSE" }
authors = [{ name = "haruki7049", email = "tontonkirikiri@gmail.com" }]
readme = "README.md"

dependencies = [
  #"django" # Example
]
